version: '3.8'

services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: ats_proxy
    ports:
      - "9080:80"
    networks:
      - pair_network
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gevent_backend
    expose:
      - "5000"
    networks:
      - pair_network
    restart: unless-stopped

networks:
  pair_network:
    driver: bridge
